# NumPy
- 고성능 과학 계산용 패키지로 강력한 N차원 배열 객체
- 반복문 없이 데이터 배열에 대한 처리, 지원 빠르고 편리
- 데이터 과학 도구에 대한 생태계의 핵심을 이루고 있음

In [1]:
import numpy as np

## 배열 생성

### 1차원 배열
- 리스트 --> 배열로 전환 [ ] 포함해야함

In [2]:
a1 = np.array([1, 2, 3, 4, 5])

In [3]:
print(a1)

[1 2 3 4 5]


- nd(n dimension) = n차원

In [4]:
print((type(a1)))

<class 'numpy.ndarray'>


In [5]:
print(a1.shape)

(5,)


In [6]:
print(a1[0])

1


- 엘리먼트 수정

In [7]:
a1[0] = 10

In [8]:
print(a1[0])

10


### 2차원 배열
- 리스트 안에 리스트가 내포된 형태 [ [ ] ]

In [9]:
a2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [10]:
print(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
print(a2.shape)

(3, 3)


In [12]:
print(a2[0,0], a2[1,2], a2[2,2])

1 6 9


### 3차원 배열

In [13]:
a3 = np.array([ [ [1, 2, 3], [4, 5, 6], [7, 8, 9] ],
                [ [1, 2, 3], [4, 5, 6], [7, 8, 9] ],
                [ [1, 2, 3,], [4, 5, 6], [7, 8, 9] ] ])

In [14]:
print(a3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [15]:
print(a3.shape)

(3, 3, 3)


## 배열 생성 및 초기화

- 0으로 10개 엘리먼트를 갖는 배열 생성

In [16]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

- 1로 3행 3열의 배열 생성

In [17]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

- ((3행 3열 배열 생성), 채워 넣을 숫자)

In [18]:
np.full((3, 3), 1.23)

array([[1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23]])

- 단위 행렬 I 를 생성 A * I = A
- 정사각형 행렬이기 때문에 인수는 하나

In [19]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

- 삼각 행렬로 행렬의 형태만 갖는 인수 하나만 가짐

In [20]:
np.tri(3)

array([[1., 0., 0.],
       [1., 1., 0.],
       [1., 1., 1.]])

- _like(a1) a1의 형태의 배열로 0을 채움

In [21]:
print(a1)
np.zeros_like(a1)

[10  2  3  4  5]


array([0, 0, 0, 0, 0])

In [22]:
print(a2)
np.ones_like(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

- np.full_like 사용때 소수를 넣으려면 dtype = float 추가

In [23]:
print(a3)
np.full_like(a3, 10.2)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


array([[[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]]])

In [24]:
np.full_like(a3, 10.2, dtype=float)

array([[[10.2, 10.2, 10.2],
        [10.2, 10.2, 10.2],
        [10.2, 10.2, 10.2]],

       [[10.2, 10.2, 10.2],
        [10.2, 10.2, 10.2],
        [10.2, 10.2, 10.2]],

       [[10.2, 10.2, 10.2],
        [10.2, 10.2, 10.2],
        [10.2, 10.2, 10.2]]])

### 생성한 값으로 배열 생성
- 값을 생성
- 그 값으로 배열 생성

- 정수 번위로 배열 생성
- 0 ~ 29 , 2 단위로

In [25]:
np.arange(0, 30, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

- 범위 내에서 균등 간격의 배열 생성
- 0 ~ 1, 5개의 균등한 배열

In [26]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

- 범위 내에서 균등 간격으로 로그 스케일로 배열 생성

In [27]:
np.logspace(0.1, 1, 20)

array([ 1.25892541,  1.40400425,  1.565802  ,  1.74624535,  1.94748304,
        2.1719114 ,  2.42220294,  2.70133812,  3.0126409 ,  3.35981829,
        3.74700446,  4.17881006,  4.66037703,  5.19743987,  5.79639395,
        6.46437163,  7.2093272 ,  8.04013161,  8.9666781 , 10.        ])

### 랜덤값으로 배열 생성

- 실수 랜덤한 수의 배열 생성( (형태) )

In [28]:
np.random.random((3, 3))

array([[0.87888454, 0.63118892, 0.17636559],
       [0.76358023, 0.29814787, 0.2800341 ],
       [0.55941883, 0.52624879, 0.69418599]])

- 일정 구간의 랜덤 정수의 배열 생성(0 ~ 10, (형태) )

In [29]:
np.random.randint(0, 10, (3, 3))

array([[9, 1, 8],
       [5, 2, 5],
       [4, 6, 6]])

- 정규 분포 랜덤한 수의 배열
- 평균 = 0 , 표준편차 = 1

In [30]:
np.random.normal(0, 1, (3,3))

array([[-0.17524782,  1.04103485, -1.62646967],
       [ 0.24262466, -0.11999611, -0.37237282],
       [-0.140023  ,  1.72594617, -0.84766044]])

- 균등분포를 고려한 랜덤한 수의 배열 생성

In [31]:
np.random.rand(3,3)

array([[0.324545  , 0.54727946, 0.9436331 ],
       [0.22960541, 0.34985014, 0.33316152],
       [0.82076164, 0.97204308, 0.79018025]])

- 표준정규분포를 고려한 랜덤한 수의 배열

In [32]:
np.random.randn(3,3)

array([[ 1.27734068,  0.44069832,  0.65268038],
       [ 0.28928832,  0.91553163,  0.87340171],
       [-0.63098031,  0.94624927, -0.22461036]])

### 표준 데이터 타입

- int 값으로 0을 줌

In [33]:
np.zeros(20, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

- bool T or F , 1 = T

In [34]:
np.ones((3, 3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

## 날짜 시간 배열 생성

- 문자열 -> 날짜열로 바꿈[D = day]

In [35]:
date = np.array('2020-01-01', dtype = np.datetime64)
date

array('2020-01-01', dtype='datetime64[D]')

- dtype 을 바꾸고 연산이 가능해짐 / 기존 날짜 + 숫자

In [36]:
date + np.arange(12)

array(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
       '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
       '2020-01-09', '2020-01-10', '2020-01-11', '2020-01-12'],
      dtype='datetime64[D]')

In [37]:
datetime = np.datetime64('2021-06-06 12:00')
datetime

numpy.datetime64('2021-06-06T12:00')

- ns = 나노 초를 의미

In [38]:
datetime = np.datetime64('2021-06-06 12:00:12.34', 'ns')
datetime

numpy.datetime64('2021-06-06T12:00:12.340000000')

## 배열 조회

In [39]:
def array_info(array):
    print(array)
    print('ndim', array.ndim)
    print('shape', array.shape)
    print('dtype', array.dtype)
    print('size', array.size)
    print('itemsize', array.itemsize)
    print('nbytes', array.nbytes)
    print('strides', array.strides)

- itemsize = item 하나가 4bytes라는 의미
- nbytes = item(4) * 엘리먼트 수(5) = 20
- strides = 10 -> 2 -> 3 -> 4-> 5 다음 엘리먼트로 넘어가는데 4bytes

In [40]:
array_info(a1)

[10  2  3  4  5]
ndim 1
shape (5,)
dtype int32
size 5
itemsize 4
nbytes 20
strides (4,)


- strides = (12, 4) 엘리먼트를 넘어가는데 4bytes
- 다른 행으로 넘어가는데 12bytes(4*3)

In [41]:
array_info(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
ndim 2
shape (3, 3)
dtype int32
size 9
itemsize 4
nbytes 36
strides (12, 4)


## 인덱싱

In [42]:
print(a1)
print(a1[0])
print(a1[2])
print(a1[-1])
print(a1[-2])

[10  2  3  4  5]
10
3
5
4


In [43]:
print(a2)
print(a2[0, 0])
print(a2[0, 2])
print(a2[1, -1])
print(a2[2, -1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
3
6
9


## 슬라이싱

- [::2] 0 ~ 끝까지 두 칸씩
- [::-1] 0 ~ 끝까지 거꾸로 1 칸씩

In [44]:
print(a1)
print(a1[0:2])
print(a1[0:])
print(a1[:1])
print(a1[::2])
print(a1[::-1])

[10  2  3  4  5]
[10  2]
[10  2  3  4  5]
[10]
[10  3  5]
[ 5  4  3  2 10]


In [45]:
print(a2)
print(a2[1])
print(a2[1, :])
print(a2[:2, :2])
print(a2[1:, ::-1])
print(a2[::-1, ::-1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[4 5 6]
[4 5 6]
[[1 2]
 [4 5]]
[[6 5 4]
 [9 8 7]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]


## 불리언 인덱싱
- 배열 각 요소의 선택 여부를 불리언으로 지정
- True 값인 인덱스의 값만 조회
- 특정 조건을 불리언 인덱싱을 주고 그 결과에 대해서 원하는 배열의 값을 받을 때 많이 사용

In [46]:
print(a1)
bi = [False, True, True, False, True]
print(a1[bi])

[10  2  3  4  5]
[2 3 5]


In [47]:
print(a2)
bi = np.random.randint(0, 2, (3, 3), dtype = bool)
print(bi)
print(a2[bi])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ True  True False]
 [False  True False]
 [False  True  True]]
[1 2 5 8 9]


## 팬시 인덱싱

In [48]:
print(a1)
print(a1[0], a1[2])
ind = [0, 2]
print(a1[ind])
ind2 = np.array([[0,1], [2,0]])
print(a1[ind2])

[10  2  3  4  5]
10 3
[10  3]
[[10  2]
 [ 3 10]]


In [49]:
print(a2)
row = np.array([0, 2]) # 0행 , 2행
col = np.array([1, 2]) # 1열 , 2열

print(1 , a2[row, col]) # 0행 1열 , 2행 2열
print(2 , a2[row, :])   # 0행 모든열, 2행 모든열
print(3 , a2[:, col])   # 모든 행, 1열, 2열
print(4 , a2[row, 1])   # 0행 2행 , 1열
print(5 , a2[2, col])   # 2행 , 1열 2열
print(6 , a2[row, 1:])  # 0행 2행 , 1열~
print(7 , a2[1: , col]) # 1행~ , 1열 2열

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1 [2 9]
2 [[1 2 3]
 [7 8 9]]
3 [[2 3]
 [5 6]
 [8 9]]
4 [2 8]
5 [8 9]
6 [[2 3]
 [8 9]]
7 [[5 6]
 [8 9]]


## 배열 값 삽입 / 수정 / 삭제 / 복사

### 삽입
- insert() 배열의 특정 위치에 값 삽입
- axis 지정하지 않으면 1차원 배열로 변환
- 추가할 방향을 axis로 지정
- 원본 배열 변경없이 새로운 배열 변환

#### insert(배열, 위치, 삽입값, axis=)
- a1 이라는 원본 배열은 insert()를 하더라도 바뀌지 않는다

In [50]:
print(a1)
b1 = np.insert(a1, 0, 55)
print(b1)
print(a1)

[10  2  3  4  5]
[55 10  2  3  4  5]
[10  2  3  4  5]


In [51]:
print(a2)
b2 = np.insert(a2, 1, 10, axis=0)
print(b2)
c2 = np.insert(a2, 1, 10, axis=1)
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3]
 [10 10 10]
 [ 4  5  6]
 [ 7  8  9]]
[[ 1 10  2  3]
 [ 4 10  5  6]
 [ 7 10  8  9]]


### 수정

In [52]:
print(a1)
a1[0] = 4
a1[1] = 5
a1[2] = 6
a1[3] = 4
a1[3] = 5
print(a1) # 1. 엘리먼트를 각각 바꿔주는 방법

a1[:1] = 9 
print(a1) # 2. 엘리먼트를 범위로 바꿔주는 방법

i = [1, 3, 4]
a1[i] = 0
print(a1) # 3. 펜시 인덱싱으로 바꾸는 방법 "리스트"

j = np.array([1, 3, 4])
a1[j] = 10
print(a1) # 4. 펜시 인덱싱으로 바꾸는 방법 "배열"

a1[j] -=5
print(a1) # 5. 펜시 인덱싱 -+*/ 숫자 연산

[10  2  3  4  5]
[4 5 6 5 5]
[9 5 6 5 5]
[9 0 6 0 0]
[ 9 10  6 10 10]
[9 5 6 5 5]


In [53]:
print(a2)
a2[0, 0] = 1
a2[1, 1] = 2
a2[2, 2] = 3
a2[0] = 1 # 해당 하는 행 모두
print(a2) # 1. 엘리먼트를 각각 바꿔주는 방법
a2[1:, 2] = 10
print(a2) # 2. 엘리먼트 범위로 바꿔주는 방법
row = np.array([0, 1])
col = np.array([1, 2])
a2[row, col] = 11
print(a2) # 3. 펜시 인덱싱으로 바꾸는 방법 "배열"

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 1 1]
 [4 2 6]
 [7 8 3]]
[[ 1  1  1]
 [ 4  2 10]
 [ 7  8 10]]
[[ 1 11  1]
 [ 4  2 11]
 [ 7  8 10]]


### 삭제

#### delete(배열, 위치, axis=)
- 배열의 특정 위치에 값 삭제
- axis 지정하지 않으면 1차원 배열로 변환
- 삭제할 방향 axis로 지정
- 원본 배열 변경 없이 새로운 배열 변환

In [54]:
print(a1)
b1 = np.delete(a1, 1)
print(b1)
print(a1)

[9 5 6 5 5]
[9 6 5 5]
[9 5 6 5 5]


In [55]:
print(a2)
b2 = np.delete(a2, 1, axis = 0) # 1 행 제거
print(b2)
c2 = np.delete(a2, 1, axis = 1) # 1 열 제거
print(c2)

[[ 1 11  1]
 [ 4  2 11]
 [ 7  8 10]]
[[ 1 11  1]
 [ 7  8 10]]
[[ 1  1]
 [ 4 11]
 [ 7 10]]


### 복사
- 리스트 자료형과 달리 배열의 슬라이스는 "복사본이 아님"
- 리스트 자료형은 복사본으로 리턴됨

In [56]:
print(a2)
print(a2[:2, :2])
a2_sub = a2[:2, :2]
print(a2_sub)
a2_sub[:, 1] = 0
print(a2_sub)         # 원본 배열 마저 바뀜

[[ 1 11  1]
 [ 4  2 11]
 [ 7  8 10]]
[[ 1 11]
 [ 4  2]]
[[ 1 11]
 [ 4  2]]
[[1 0]
 [4 0]]


In [57]:
print(a2)
a2_sub_copy = a2[:2, :2].copy()
print(a2_sub_copy)
a2_sub_copy[:, 1] = 0
print(a2_sub_copy)
print(a2)            # 원본 바뀜 X

[[ 1  0  1]
 [ 4  0 11]
 [ 7  8 10]]
[[1 0]
 [4 0]]
[[1 0]
 [4 0]]
[[ 1  0  1]
 [ 4  0 11]
 [ 7  8 10]]


## 배열 변환

### 배열 전치 및 축 변경

In [61]:
print(a2)
print(a2.T)

[[ 1  0  1]
 [ 4  0 11]
 [ 7  8 10]]
[[ 1  4  7]
 [ 0  0  8]
 [ 1 11 10]]


In [62]:
print(a3)
print(a3.swapaxes(1, 0))
print(a3)
print(a3.swapaxes(0, 1))

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[[1 2 3]
  [1 2 3]
  [1 2 3]]

 [[4 5 6]
  [4 5 6]
  [4 5 6]]

 [[7 8 9]
  [7 8 9]
  [7 8 9]]]
[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[[1 2 3]
  [1 2 3]
  [1 2 3]]

 [[4 5 6]
  [4 5 6]
  [4 5 6]]

 [[7 8 9]
  [7 8 9]
  [7 8 9]]]


### 배열 재구조화

- .reshape 1차원 -> 2차원

In [63]:
n1 = np.arange(1, 10)
print(n1)
print(n1.reshape(3, 3))

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [64]:
print(n1)
print(n1[np.newaxis, :5]) 
print(n1[:5, np.newaxis])

[1 2 3 4 5 6 7 8 9]
[[1 2 3 4 5]]
[[1]
 [2]
 [3]
 [4]
 [5]]


## 배열 크기 변경

### 모양 변경
- .resize(( , ))

In [67]:
n2 = np.random.randint(0, 10, (2, 5))
print(n2)

n2.resize((5, 2))
print(n2)

[[3 2 3 4 6]
 [8 9 4 4 6]]
[[3 2]
 [3 4]
 [6 8]
 [9 4]
 [4 6]]


- 배열 크기 증가

In [69]:
n2.resize((5, 5))
print(n2)

[[3 2 3 4 6]
 [8 9 4 4 6]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


## 배열 추가

- .append
- axis 지정이 따로 없으면 1차원 배열 출력

In [71]:
a2 = np.arange(1, 10).reshape(3, 3)
print(a2)
b2 = np.arange(10, 19).reshape(3, 3)
print(b2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [73]:
c2 = np.append(a2, b2)
print(c2)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


In [74]:
c2 = np.append(a2, b2, axis = 1)
print(c2)

[[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]


In [75]:
c2 = np.append(a2, b2, axis = 0)
print(c2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


## 배열 연결

- np.concatenate([ ])

In [77]:
a1 = np.array([1, 3, 5])
b1 = np.array([2, 4, 6])
np.concatenate([a1, b1])

array([1, 3, 5, 2, 4, 6])

In [78]:
c1 = np.array([7, 8, 9])
np.concatenate([a1, b1, c1])

array([1, 3, 5, 2, 4, 6, 7, 8, 9])

In [81]:
a2 = np.array([[1,2,3],
               [4,5,6]])
np.concatenate([a2, a2]) 

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [82]:
a2 = np.array([[1,2,3],
               [4,5,6]])
np.concatenate([a2, a2], axis = 1) 

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

- vstack([ , ])
- 수직스택
- 1차원으로 연결

In [83]:
np.vstack([a2, a2])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

- hstack([ , ])
- 수평스택
- 2차원으로 연결

In [85]:
np.hstack([a2, a2])

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

- dstack([ , ])
- 깊이스택
- 3차원으로 연결

In [86]:
np.dstack([a2, a2])

array([[[1, 1],
        [2, 2],
        [3, 3]],

       [[4, 4],
        [5, 5],
        [6, 6]]])

- stack([ , ])
- 새로운 차원으로 연결
- 2 -> 3차원으로

In [87]:
np.stack([a2, a2])

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

## 배열 분할

- split()

In [88]:
a1 = np.arange(0, 10)
print(a1)
b1, c1 = np.split(a1, [5]) # 5번째 엘리먼트를 기준으로 나눔
print(b1, c1)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4] [5 6 7 8 9]


In [91]:
b1, c1, d1, e1, f1 = np.split(a1, [2, 4, 6, 8])
print(b1, c1, d1, e1, f1)

[0 1] [2 3] [4 5] [6 7] [8 9]


- vsplit() 
- 수직분할, 1차원으로 분할

In [94]:
a2 = np.arange(1, 10).reshape(3, 3)
print(a2)

b2, c2 = np.vsplit(a2, [2]) # 0, 1행/ 2행이 스플릿 됨
print(b2, c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]] [[7 8 9]]


- vsplit() 
- 수평분할, 2차원으로 분할

In [106]:
a2 = np.arange(1, 10).reshape(3, 3)
print(a2)

b2, c2 = np.hsplit(a2, [2])
print(b2, c2 , sep = '\n')

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]
 [7 8]]
[[3]
 [6]
 [9]]


## 배열연산(NumPy의 장점)
- 배열연산은 각 엘리먼트 연산(벡터화)을 사용
- 일반적으로 범용 함수를 통해 구현
- 배열 요소에 대한 반복적인 계산 효율적 수행

- 브로드 캐스팅(모양이 다르더라도 분배 법칙으로 계산됨)

In [109]:
print(1, np.array([1,2,3]) + np.array([5]))
print(2, np.array([1,2,3]) + 5)
print(3, np.array([1,2,3]) + np.array([[1,2,3],[4,5,6],[7,8,9]]))
print(4, np.array([1,2,3]) + np.arange(1,10).reshape(3,3))
print(5, np.array([1,2,3]) + np.array([[1],[2],[3]]))
print(6, np.array([1,2,3]) + np.array([1,2,3]).reshape(3,1))

1 [6 7 8]
2 [6 7 8]
3 [[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]
4 [[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]
5 [[2 3 4]
 [3 4 5]
 [4 5 6]]
6 [[2 3 4]
 [3 4 5]
 [4 5 6]]


## 산술연산

In [110]:
a1 = np.arange(1, 10)
print(a1)
print(a1 + 1) 
print(np.add(a1, 10))       # 연산자 + 와 같은 역할
print(a1 - 1)
print(np.subtract(a1, 10))  # 연산자 - 와 같은 역할
print(-a1)
print(np.negative(a1))      # -a1와 같은 역할
print(a1 * 2)
print(np.multiply(a1, 2))   # 연산자 * 와 같은 역할
print(a1 / 2)
print(np.divide(a1, 2))     # 연산자 / 와 같은 역할
print(a1 // 2)
print(np.floor_divide(a1,2)) # 연산자 // 와 같은 역할 (몫)  
print(a1 ** 2)
print(np.power(a1,2))        # 연산자 ** 와 같은 역할
print(a1 % 2)
print(np.mod(a1,2))          # 연산자 % 와 같은 역할(나머지)

[1 2 3 4 5 6 7 8 9]
[ 2  3  4  5  6  7  8  9 10]
[11 12 13 14 15 16 17 18 19]
[0 1 2 3 4 5 6 7 8]
[-9 -8 -7 -6 -5 -4 -3 -2 -1]
[-1 -2 -3 -4 -5 -6 -7 -8 -9]
[-1 -2 -3 -4 -5 -6 -7 -8 -9]
[ 2  4  6  8 10 12 14 16 18]
[ 2  4  6  8 10 12 14 16 18]
[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[0 1 1 2 2 3 3 4 4]
[0 1 1 2 2 3 3 4 4]
[ 1  4  9 16 25 36 49 64 81]
[ 1  4  9 16 25 36 49 64 81]
[1 0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0 1]


In [111]:
a1 = np.arange(1, 10)
print(a1)
b1 = np.random.randint(1,10, size =9) # size = 엘리먼트 개수
print(b1)
print(a1 + b1)
print(a1 - b1)
print(a1 * b1)
print(a1 / b1)
print(a1 // b1)
print(a1 ** b1)
print(a1 % b1)

[1 2 3 4 5 6 7 8 9]
[1 3 5 6 7 1 6 7 7]
[ 2  5  8 10 12  7 13 15 16]
[ 0 -1 -2 -2 -2  5  1  1  2]
[ 1  6 15 24 35  6 42 56 63]
[1.         0.66666667 0.6        0.66666667 0.71428571 6.
 1.16666667 1.14285714 1.28571429]
[1 0 0 0 0 6 1 1 1]
[      1       8     243    4096   78125       6  117649 2097152 4782969]
[0 2 3 4 5 0 1 1 2]


In [112]:
a2 = np.arange(1,10).reshape(3,3)
print(a2)
b2 = np.random.randint(1, 10 ,size=(3,3))
print(b2)
print(a2 + b2)
print(a2 - b2)
print(a2 * b2)
print(a2 / b2)
print(a2 // b2)
print(a2 ** b2)
print(a2 % b2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[3 7 5]
 [2 5 8]
 [9 8 4]]
[[ 4  9  8]
 [ 6 10 14]
 [16 16 13]]
[[-2 -5 -2]
 [ 2  0 -2]
 [-2  0  5]]
[[ 3 14 15]
 [ 8 25 48]
 [63 64 36]]
[[0.33333333 0.28571429 0.6       ]
 [2.         1.         0.75      ]
 [0.77777778 1.         2.25      ]]
[[0 0 0]
 [2 1 0]
 [0 1 2]]
[[       1      128      243]
 [      16     3125  1679616]
 [40353607 16777216     6561]]
[[1 2 3]
 [0 0 6]
 [7 0 1]]


### 절대값 함수

In [113]:
a1 = np.random.randint(-10,10, 5)
print(a1)
print(np.abs(a1))

[ 6 -4 -6  6  9]
[6 4 6 6 9]


### 제곱 / 제곱근 함수

In [114]:
print(a1)
print(np.square(a1)) # 제곱
print(np.sqrt(a1))   # 제곱근

[ 6 -4 -6  6  9]
[36 16 36 36 81]
[2.44948974        nan        nan 2.44948974 3.        ]


<ipython-input-114-f3302d4ed139>:3: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(a1))   # 제곱근


### 지수와 로그 함수

In [115]:
a1 = np.random.randint(1,10, 5)
print(a1)
print(np.exp(a1))
print(np.exp2(a1))
print(np.power(a1,2))

[1 9 2 4 8]
[2.71828183e+00 8.10308393e+03 7.38905610e+00 5.45981500e+01
 2.98095799e+03]
[  2. 512.   4.  16. 256.]
[ 1 81  4 16 64]


## 집계함수

### sum()

In [120]:
a2 = np.random.randint(1,10, (3,3))
print(a2)
print(a2.sum(), np.sum(a2))        # 두 형태 모두 사용 가능
print(a2.sum(axis = 0), np.sum(a2, axis=0)) # 행 (세로)
print(a2.sum(axis = 1), np.sum(a2, axis=1)) # 열 (가로)

[[3 5 4]
 [7 9 3]
 [5 5 6]]
47 47
[15 19 13] [15 19 13]
[12 19 16] [12 19 16]


### cumsum()
- 누적합 계산

In [124]:
print(a2)
print(a2.cumsum())
print(a2.cumsum(axis = 0))
print(a2.cumsum(axis = 1))

[[3 5 4]
 [7 9 3]
 [5 5 6]]
[ 3  8 12 19 28 31 36 41 47]
[[ 3  5  4]
 [10 14  7]
 [15 19 13]]
[[ 3  8 12]
 [ 7 16 19]
 [ 5 10 16]]


### diff
- 차분계산

In [126]:
print(a2)
print(np.diff(a2)) # 0행 0열 3 -> 3 : 0 / 3 -> 6 : 3
print(np.diff(a2, axis = 0)) # 행(세로)
print(np.diff(a2, axis = 1)) # 열(가로)

[[3 5 4]
 [7 9 3]
 [5 5 6]]
[[ 2 -1]
 [ 2 -6]
 [ 0  1]]
[[ 4  4 -1]
 [-2 -4  3]]
[[ 2 -1]
 [ 2 -6]
 [ 0  1]]


### prod()
- 곱 계산

In [127]:
print(a2)
print(np.prod(a2))
print(np.prod(a2, axis = 0))
print(np.prod(a2, axis = 1))

[[3 5 4]
 [7 9 3]
 [5 5 6]]
1701000
[105 225  72]
[ 60 189 150]


### cumprod()
- 누적 곱 계산

In [129]:
print(a2)
print(np.cumprod(a2))
print(np.cumprod(a2, axis = 0)) # 행 (세로)
print(np.cumprod(a2, axis = 1)) # 열 (가로)

[[3 5 4]
 [7 9 3]
 [5 5 6]]
[      3      15      60     420    3780   11340   56700  283500 1701000]
[[  3   5   4]
 [ 21  45  12]
 [105 225  72]]
[[  3  15  60]
 [  7  63 189]
 [  5  25 150]]


### dot() / matmul()
- 점곱, 행렬곱 계산
- dot는 행렬과 상수의 곱셈을 허용한다
- matmul은 Error를 일으킨다

In [132]:
print(a2)
b2 = np.ones_like(a2)
print(b2)
print(np.dot(a2, b2))     # 일반 행렬의 곱(n X a * a X s)
print(np.matmul(a2, b2))
np.dot(a2, 2)

[[3 5 4]
 [7 9 3]
 [5 5 6]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[12 12 12]
 [19 19 19]
 [16 16 16]]
[[12 12 12]
 [19 19 19]
 [16 16 16]]


array([[ 6, 10,  8],
       [14, 18,  6],
       [10, 10, 12]])

### tensordot() 텐서곱 계산

In [133]:
print(a2)
print(b2)
print(np.tensordot(a2,b2))   
print(np.tensordot(a2,b2,axes = 0))   
print(np.tensordot(a2,b2,axes = 1)) 

[[3 5 4]
 [7 9 3]
 [5 5 6]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
47
[[[[3 3 3]
   [3 3 3]
   [3 3 3]]

  [[5 5 5]
   [5 5 5]
   [5 5 5]]

  [[4 4 4]
   [4 4 4]
   [4 4 4]]]


 [[[7 7 7]
   [7 7 7]
   [7 7 7]]

  [[9 9 9]
   [9 9 9]
   [9 9 9]]

  [[3 3 3]
   [3 3 3]
   [3 3 3]]]


 [[[5 5 5]
   [5 5 5]
   [5 5 5]]

  [[5 5 5]
   [5 5 5]
   [5 5 5]]

  [[6 6 6]
   [6 6 6]
   [6 6 6]]]]
[[12 12 12]
 [19 19 19]
 [16 16 16]]


### cross() 벡터곱

In [134]:
x = [1,2,3]
y = [4,5,6]
print(np.cross(x,y))

[-3  6 -3]


### inner()/outer() 내적/외적

In [135]:
print(a2)
print(b2)
print(np.inner(a2, b2)) # dot() 똑같은 결과 행렬의 곱
print(np.outer(a2, b2)) # dot() 을 바깥으로 펼쳐냄)

[[3 5 4]
 [7 9 3]
 [5 5 6]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[12 12 12]
 [19 19 19]
 [16 16 16]]
[[3 3 3 3 3 3 3 3 3]
 [5 5 5 5 5 5 5 5 5]
 [4 4 4 4 4 4 4 4 4]
 [7 7 7 7 7 7 7 7 7]
 [9 9 9 9 9 9 9 9 9]
 [3 3 3 3 3 3 3 3 3]
 [5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5]
 [6 6 6 6 6 6 6 6 6]]


### mean()
- 평균 계산

In [137]:
print(a2)
print(a2.mean())
print(a2.mean(axis = 0))
print(a2.mean(axis = 1))

[[3 5 4]
 [7 9 3]
 [5 5 6]]
5.222222222222222
[5.         6.33333333 4.33333333]
[4.         6.33333333 5.33333333]


### std()
- 표준 편차 계산

In [138]:
print(a2)
print(a2.std())
print(a2.std(axis = 0))
print(a2.std(axis = 1))

[[3 5 4]
 [7 9 3]
 [5 5 6]]
1.8121673811444545
[1.63299316 1.88561808 1.24721913]
[0.81649658 2.49443826 0.47140452]


### var()
- 분산

In [140]:
print(a2)
print(a2.var())
print(a2.var(axis=0))
print(a2.var(axis=1))

[[3 5 4]
 [7 9 3]
 [5 5 6]]
3.283950617283951
[2.66666667 3.55555556 1.55555556]
[0.66666667 6.22222222 0.22222222]


### min()
- 최소값

In [141]:
print(a2)
print(np.min(a2))
print(np.min(a2, axis = 0))
print(np.min(a2, axis = 1))

[[3 5 4]
 [7 9 3]
 [5 5 6]]
3
[3 5 3]
[3 3 5]


### max()
- 최대값

In [142]:
print(a2)
print(np.max(a2))
print(np.max(a2, axis = 0))
print(np.max(a2, axis = 1))

[[3 5 4]
 [7 9 3]
 [5 5 6]]
9
[7 9 6]
[5 9 6]


### argmin()
- 최소값 인덱스

In [143]:
print(a2)
print(np.argmin(a2))
print(np.argmin(a2, axis = 0)) # 세로 (다른 행)
print(np.argmin(a2, axis = 1)) # 가로 (다른 열)

[[3 5 4]
 [7 9 3]
 [5 5 6]]
0
[0 0 1]
[0 2 0]


### argmax() 
- 최대값 인덱스

In [144]:
print(a2)
print(np.argmax(a2))
print(np.argmax(a2, axis = 1))
print(np.argmax(a2, axis = 0))

[[3 5 4]
 [7 9 3]
 [5 5 6]]
4
[1 1 2]
[1 1 2]


### median
- 중앙값

In [145]:
print(a2)
print(np.median(a2))
print(np.median(a2, axis = 0))
print(np.median(a2, axis = 1))

[[3 5 4]
 [7 9 3]
 [5 5 6]]
5.0
[5. 5. 4.]
[4. 7. 5.]


### percentile() 백분위수

In [146]:
a1 = np.array([0, 1, 2, 3])
print(a1)

print(np.percentile(a1, [0, 20, 40, 60, 80, 100],
                    interpolation='linear'))
print(np.percentile(a1, [0, 20, 40, 60, 80, 100],
                    interpolation='higher'))
print(np.percentile(a1,[0, 20, 40, 60, 80, 100],
                   interpolation='lower'))
print(np.percentile(a1,[0, 20, 40, 60, 80, 100],
                   interpolation='nearest'))
print(np.percentile(a1,[0, 20, 40, 60, 80, 100],
                   interpolation='midpoint'))

[0 1 2 3]
[0.  0.6 1.2 1.8 2.4 3. ]
[0 1 2 2 3 3]
[0 0 1 1 2 3]
[0 1 1 2 2 3]
[0.  0.5 1.5 1.5 2.5 3. ]


In [147]:
a1 = np.array([0,1,2,3])
print(a1)
print(np.percentile(a1, 30)) # a1 배열에 30% 지점

[0 1 2 3]
0.8999999999999999


### any()
- 이 중에서 하나라도 True면 True

In [149]:
a2 = np.array([[False, False, True],
               [True, True, True],
               [False, True, True]])

print(a2)
print(np.any(a2))          
print(np.any(a2, axis = 0))
print(np.any(a2, axis = 1))

[[False False  True]
 [ True  True  True]
 [False  True  True]]
True
[ True  True  True]
[ True  True  True]


### all()
- 모든 값이 True 여야 True

In [151]:
a2 = np.array([[False, False, True],
               [True, True, True],
               [False, True, True]])

print(a2)
print(np.all(a2))
print(np.all(a2, axis = 0))
print(np.all(a2, axis = 1))

[[False False  True]
 [ True  True  True]
 [False  True  True]]
False
[False False  True]
[False  True False]


## 비교 연산
- 위치에 대해서만 True 값을 줌

In [154]:
a1 = np.arange(1,10)
print(a1)
print(a1 == 5)
print(a1 != 5)
print(a1 <= 5)
print(a1 > 5)

[1 2 3 4 5 6 7 8 9]
[False False False False  True False False False False]
[ True  True  True  True False  True  True  True  True]
[ True  True  True  True  True False False False False]
[False False False False False  True  True  True  True]


In [155]:
a2 = np.arange(1,10).reshape(3,3)
print(a2)
print(np.sum(a2))
print(np.count_nonzero(a2 > 5)) # 6,7,8,9 4개
print(np.sum(a2 > 5))           # 5 초과인것 4개
print(np.sum(a2 > 5, axis=0))   # 세로에서 5 초과인 개수
print(np.sum(a2 > 5, axis=1))   # 가로에서 5 초과인 개수
print(np.any(a2 > 5, axis=0))
print(np.any(a2 > 5, axis=1))
print(np.all(a2 > 5, axis=0))
print(np.all(a2 > 5, axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
4
4
[1 1 2]
[0 1 3]
[ True  True  True]
[False  True  True]
[False False False]
[False False  True]


### np.isclose()
- 가깝나요?

In [157]:
a1 = np.array([1, 2, 3, 4, 5])
print(a1)
b1 = np.array([1, 2, 3, 4, 6])
print(b1)
print(np.isclose(a1, b1))

[1 2 3 4 5]
[1 2 3 4 6]
[ True  True  True  True False]


### np.nan,inf,ninf
- na 인것
- 무한대인것
- 무한대가 아닌것

In [162]:
a1 = np.array([np.nan, 2, np.inf, 4, np.NINF])
print(a1)
print(np.isnan(a1))
print(np.isinf(a1))
print(np.isfinite(a1))

[ nan   2.  inf   4. -inf]
[ True False False False False]
[False False  True False  True]
[False  True False  True False]


## 불리언 연산자 (&, |, ^, ~)

In [163]:
a2 = np.arange(1,10).reshape(3,3)
print(a2)
print(1 ,(a2 > 5) & (a2 < 8))
print(1 ,a2[(a2 > 5) & (a2 < 8)]) # 불리언 인덱싱

print(2 ,(a2 > 5) | (a2 < 8))
print(2 ,a2[(a2 > 5) | (a2 < 8)])

print(3 ,(a2 > 5) ^ (a2 < 8))     # 해당하는 엘리먼트 이외 값
print(3 ,a2[(a2 > 5) ^ (a2 < 8)]) # [6 7]

print(4 , ~ (a2 > 5))             # ~ not을 의미
print(4 ,a2[~(a2 > 5)])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1 [[False False False]
 [False False  True]
 [ True False False]]
1 [6 7]
2 [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
2 [1 2 3 4 5 6 7 8 9]
3 [[ True  True  True]
 [ True  True False]
 [False  True  True]]
3 [1 2 3 4 5 8 9]
4 [[ True  True  True]
 [ True  True False]
 [False False False]]
4 [1 2 3 4 5]


## 배열 정렬

## np.sort()

In [167]:
a1 = np.random.randint(1, 10, 10)
print(a1)
print(np.sort(a1))
print(a1)
print(np.argsort(a1)) # 정렬에 필요한 인덱싱출력
                      # 1번째 있는 2 가 제일 작고
                      # 9번째 있는 3 이 그 다음이야

print(a1)             # 원본 유지

print(a1.sort())      # 원본 자체를 정렬
print(a1)

[2 9 3 5 4 3 7 2 3 2]
[2 2 2 3 3 3 4 5 7 9]
[2 9 3 5 4 3 7 2 3 2]
[0 7 9 2 5 8 4 3 6 1]
[2 9 3 5 4 3 7 2 3 2]
None
[2 2 2 3 3 3 4 5 7 9]


In [168]:
a2 = np.random.randint(1, 10, (3,3))
print(a2)
print(np.sort(a2, axis=0))
print(np.sort(a2, axis=1))

[[1 6 1]
 [8 3 8]
 [4 1 9]]
[[1 1 1]
 [4 3 8]
 [8 6 9]]
[[1 1 6]
 [3 8 8]
 [1 4 9]]


### np.partition() 
- 배열에서 k 개의 작은 값을 반환

In [169]:
a1 = np.random.randint(1, 10, 10)
print(a1)
print(np.partition(a1, 3)) # 작은 값 게개를 앞에 위치 시킴

[9 3 5 8 1 7 8 1 9 2]
[1 1 2 3 5 7 8 8 9 9]


In [170]:
a2 = np.random.randint(1, 10, (5,5))
print(a2)
print(1 ,np.partition(a2, 3)) # 각 행의 작은 값 3개로 바꿔줌
print(2 ,np.partition(a2, 3, axis=0))
print(3 ,np.partition(a2, 3, axis=1))

[[7 8 1 5 5]
 [8 2 7 8 6]
 [7 8 1 9 5]
 [8 3 6 9 4]
 [6 7 3 3 3]]
1 [[5 1 5 7 8]
 [2 6 7 8 8]
 [1 5 7 8 9]
 [3 4 6 8 9]
 [3 3 3 6 7]]
2 [[6 3 1 3 4]
 [7 7 1 5 3]
 [7 2 3 8 5]
 [8 8 6 9 5]
 [8 8 7 9 6]]
3 [[5 1 5 7 8]
 [2 6 7 8 8]
 [1 5 7 8 9]
 [3 4 6 8 9]
 [3 3 3 6 7]]
