In [1]:
# 라이브러리 적용
import tensorflow as tf
import pandas as pd


In [2]:
# 데이터 로드
path = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
iris = pd.read_csv(path)
iris.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭      품종
0   5.1  3.5    1.4   0.2  setosa
1   4.9  3.0    1.4   0.2  setosa
2   4.7  3.2    1.3   0.2  setosa
3   4.6  3.1    1.5   0.2  setosa
4   5.0  3.6    1.4   0.2  setosa

In [3]:
# 원핫인코딩
iris = pd.get_dummies(iris)

In [8]:
# 종속변수, 독립변수 분리
X = iris.drop(['품종_setosa', '품종_versicolor', '품종_virginica'], axis=1)
y = iris[['품종_setosa', '품종_versicolor', '품종_virginica']]

In [9]:
print(X.shape, y.shape)

(150, 4) (150, 3)


In [14]:
# 모델 구조 만들기
Input = tf.keras.layers.Input(shape=[4])
Output = tf.keras.layers.Dense(3, activation='softmax')(Input) # 종속변수 3개, 분류 모델 활성함수 지정 
model = tf.keras.models.Model(Input, Output)
model.compile(loss='categorical_crossentropy', metrics='accuracy')

- 분류 모델이 분류를 추측하는 것도 확률로 표현함
- 이렇게 만들어주는 활성화 함수가 softmax, sigmoid 임
  - softmax -> multi-classification, 확률의 총합 = 1
  - sigmoid -> binary-classification




In [17]:
# 모델 학습
model.fit(X, y, epochs=1000, verbose=0)
model.fit(X, y, epochs=10)

Epoch 1/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0965 - accuracy: 0.9733
Epoch 2/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0961 - accuracy: 0.9800
Epoch 3/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0961 - accuracy: 0.9800
Epoch 4/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0962 - accuracy: 0.9800
Epoch 5/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0964 - accuracy: 0.9800
Epoch 6/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0960 - accuracy: 0.9800
Epoch 7/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0959 - accuracy: 0.9733
Epoch 8/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0960 - accuracy: 0.9800
Epoch 9/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0961 - accuracy: 0.9800
Epoch 10/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0964 - accuracy: 0.9800


In [18]:
# 모델 이용
print(model.predict(X[:5]))
print(y[:5])

[[9.9997544e-01 2.4507599e-05 4.8435969e-12]
 [9.9976689e-01 2.3310541e-04 1.6665946e-10]
 [9.9993098e-01 6.8978094e-05 3.6506055e-11]
 [9.9970078e-01 2.9927891e-04 3.6141190e-10]
 [9.9998295e-01 1.7031974e-05 3.2584799e-12]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0


In [19]:
print(model.predict(X[-5:]))
print(y[-5:])

[[4.8863324e-10 3.9308351e-02 9.6069169e-01]
 [1.7489090e-09 1.0124628e-01 8.9875376e-01]
 [5.1844515e-09 1.2941112e-01 8.7058890e-01]
 [4.5434403e-10 2.4170063e-02 9.7582996e-01]
 [1.8573855e-08 1.7375797e-01 8.2624203e-01]]
     품종_setosa  품종_versicolor  품종_virginica
145          0              0             1
146          0              0             1
147          0              0             1
148          0              0             1
149          0              0             1


In [20]:
# w, b 출력
print(model.get_weights())

[array([[ 1.3228853 ,  0.7039937 , -0.900654  ],
       [ 5.034706  ,  0.77682745, -1.1528847 ],
       [-6.0115275 , -1.1108233 ,  1.246766  ],
       [-6.375637  , -2.0622056 ,  3.3076963 ]], dtype=float32), array([ 2.716764 ,  2.4355114, -2.438234 ], dtype=float32)]
