In [2]:
# 라이브러리 사용
import tensorflow as tf
import pandas as pd

- 기존에는 퍼셉트론, 신경망 하나로 모델을 만들었음 
- 히든레이어를 넣어서 우리가 흔히 말하는 딥러닝 실습을 진행

# 보스턴 집값 예측 

In [4]:
# 데이터 로드
path = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv'
boston = pd.read_csv(path)
boston

crim    zn  indus  chas    nox  ...  tax  ptratio       b  lstat  medv
0    0.00632  18.0   2.31     0  0.538  ...  296     15.3  396.90   4.98  24.0
1    0.02731   0.0   7.07     0  0.469  ...  242     17.8  396.90   9.14  21.6
2    0.02729   0.0   7.07     0  0.469  ...  242     17.8  392.83   4.03  34.7
3    0.03237   0.0   2.18     0  0.458  ...  222     18.7  394.63   2.94  33.4
4    0.06905   0.0   2.18     0  0.458  ...  222     18.7  396.90   5.33  36.2
..       ...   ...    ...   ...    ...  ...  ...      ...     ...    ...   ...
501  0.06263   0.0  11.93     0  0.573  ...  273     21.0  391.99   9.67  22.4
502  0.04527   0.0  11.93     0  0.573  ...  273     21.0  396.90   9.08  20.6
503  0.06076   0.0  11.93     0  0.573  ...  273     21.0  396.90   5.64  23.9
504  0.10959   0.0  11.93     0  0.573  ...  273     21.0  393.45   6.48  22.0
505  0.04741   0.0  11.93     0  0.573  ...  273     21.0  396.90   7.88  11.9

[506 rows x 14 columns]

In [8]:
# 종속변수, 독립변수
X = boston.drop(['medv'], axis=1)
y = boston[['medv']]

In [10]:
# 모델의 구조 생성
Input = tf.keras.layers.Input(shape=[13])
H = tf.keras.layers.Dense(10, activation='swish')(Input) # 노드 10개 생성, 활성화 함수 "스위시"
Output = tf.keras.layers.Dense(1)(H)
model = tf.keras.models.Model(Input, Output)
model.compile(loss='mse')

In [16]:
# 확인
model.summary() # param 가중치 w, b 개수

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 13)]              0         
                                                                 
 dense (Dense)               (None, 10)                140       
                                                                 
 dense_1 (Dense)             (None, 1)                 11        
                                                                 
Total params: 151
Trainable params: 151
Non-trainable params: 0
_________________________________________________________________


In [23]:
# 학습
model.fit(X, y, epochs=1000, verbose=0)
model.fit(X, y, epochs=10)

Epoch 1/10
16/16 [==============================] - 0s 2ms/step - loss: 16.4698
Epoch 2/10
16/16 [==============================] - 0s 2ms/step - loss: 14.9310
Epoch 3/10
16/16 [==============================] - 0s 2ms/step - loss: 16.0275
Epoch 4/10
16/16 [==============================] - 0s 2ms/step - loss: 15.1992
Epoch 5/10
16/16 [==============================] - 0s 2ms/step - loss: 14.8062
Epoch 6/10
16/16 [==============================] - 0s 2ms/step - loss: 15.4080
Epoch 7/10
16/16 [==============================] - 0s 2ms/step - loss: 14.9308
Epoch 8/10
16/16 [==============================] - 0s 2ms/step - loss: 15.7732
Epoch 9/10
16/16 [==============================] - 0s 2ms/step - loss: 15.5339
Epoch 10/10
16/16 [==============================] - 0s 2ms/step - loss: 16.1041


In [24]:
# 예측
print(model.predict(X[:5]))
print(y[:5])

[[28.162998]
 [23.629519]
 [30.10679 ]
 [29.27888 ]
 [29.481266]]
   medv
0  24.0
1  21.6
2  34.7
3  33.4
4  36.2


# 아이리스 품종 분류

In [25]:
# 데이터 로드
path = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
iris = pd.read_csv(path)

In [27]:
# 원핫 인코딩
iris = pd.get_dummies(iris)
iris

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_setosa  품종_versicolor  품종_virginica
0     5.1  3.5    1.4   0.2          1              0             0
1     4.9  3.0    1.4   0.2          1              0             0
2     4.7  3.2    1.3   0.2          1              0             0
3     4.6  3.1    1.5   0.2          1              0             0
4     5.0  3.6    1.4   0.2          1              0             0
..    ...  ...    ...   ...        ...            ...           ...
145   6.7  3.0    5.2   2.3          0              0             1
146   6.3  2.5    5.0   1.9          0              0             1
147   6.5  3.0    5.2   2.0          0              0             1
148   6.2  3.4    5.4   2.3          0              0             1
149   5.9  3.0    5.1   1.8          0              0             1

[150 rows x 7 columns]

In [29]:
# 종속변수, 독립변수
X = iris.drop(['품종_setosa', '품종_versicolor', '품종_virginica'], axis=1)
y = iris[['품종_setosa', '품종_versicolor', '품종_virginica']]

In [32]:
# 모델의 구조 생성
Input = tf.keras.layers.Input(shape=[4])
H = tf.keras.layers.Dense(8, activation='swish')(Input) # 노드 8개 갖는 히든레이어 3개 생성 
H = tf.keras.layers.Dense(8, activation='swish')(H)
H = tf.keras.layers.Dense(8, activation='swish')(H)
Output = tf.keras.layers.Dense(3, activation='softmax')(H)
model = tf.keras.models.Model(Input, Output)
model.compile(loss='categorical_crossentropy', metrics='accuracy')

In [34]:
# 확인
model.summary()

Model: "model_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_3 (InputLayer)        [(None, 4)]               0         
                                                                 
 dense_6 (Dense)             (None, 8)                 40        
                                                                 
 dense_7 (Dense)             (None, 8)                 72        
                                                                 
 dense_8 (Dense)             (None, 8)                 72        
                                                                 
 dense_9 (Dense)             (None, 3)                 27        
                                                                 
Total params: 211
Trainable params: 211
Non-trainable params: 0
_________________________________________________________________


In [33]:
# 학습
model.fit(X, y, epochs=10000, verbose=0)
model.fit(X, y, epochs=10)

Epoch 1/10
5/5 [==============================] - 0s 4ms/step - loss: 0.0325 - accuracy: 0.9800
Epoch 2/10
5/5 [==============================] - 0s 4ms/step - loss: 0.0353 - accuracy: 0.9867
Epoch 3/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0451 - accuracy: 0.9800
Epoch 4/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0376 - accuracy: 0.9867
Epoch 5/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0335 - accuracy: 0.9867
Epoch 6/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0327 - accuracy: 0.9867
Epoch 7/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0338 - accuracy: 0.9867
Epoch 8/10
5/5 [==============================] - 0s 4ms/step - loss: 0.0403 - accuracy: 0.9800
Epoch 9/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0336 - accuracy: 0.9867
Epoch 10/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0327 - accuracy: 0.9867


In [35]:
print(model.predict(X[:5]))
print(y[:5])

[[1.0000000e+00 2.0467281e-25 3.8598973e-09]
 [1.0000000e+00 2.0698781e-22 2.0322904e-08]
 [1.0000000e+00 8.2855465e-24 5.2674278e-09]
 [1.0000000e+00 3.9151929e-22 1.7426622e-08]
 [1.0000000e+00 8.9744003e-26 2.6050304e-09]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0
